[package]
name = "s3-zip"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] } # async runtime
warp = "0.3" # web framework
rusoto_core = "0.47" # AWS SDK core
rusoto_s3 = "0.47" # AWS SDK S3
zip = "0.5" # for creating zip files
bytes = "1.0" # to work with byte arrays